### ISSUE TITLE
Missing emoji

### ISSUE THREAD

**Issue by robertmarkbram** [vdurmont/emoji-java#11]
Hello,

Apple added a bunch more emoji in October (http://blog.emojipedia.org/ios-9-1-emoji-changelog/). I tried to test by outputting all of them, extracting the message from my phone with TouchCopy and then running the result through your parser. Pretty good overall, but I noticed a few that were missing.

Also, I noticed a few that don't get picked up but which seem to have symbols already in a few editors, like ☺☮✡. Can we get these picked up by your parser too? In my project, these files are being saved to ANSI Latin 1 and I would like replace all symbols with some textual representation.

[EmojiTest.java.txt](https://github.com/vdurmont/emoji-java/files/34544/EmojiTest.java.txt)

Rob
:)

**Comment by maxsap** [comment]
+1

**Comment by vdurmont** [comment]
Hi!

Thanks for raising the issue and sorry for not answering faster.
I started a new branch (https://github.com/vdurmont/emoji-java/tree/new-emojis-ios9.1) to add the new emojis.
I already added the "faces" and "hands" (see commit https://github.com/vdurmont/emoji-java/commit/202abaf19b72a0a7afab6bc66e1a7b21236d7a6d) and we still need to add the other ones to the database. It's a long work :)

Any help is welcome!

Regarding the david cross, the slightly smiling face and the peace symbol, they will be added on this branch so I think they're going to get picked up after this. Let me know if I misunderstood.

**Comment by robertmarkbram** [comment]
You understood perfectly! I would help, but I am umm.. washing my hair that night, yeah, sorry. Anyway, looking forward to the next iteration. :)

**Comment by sunnykgupta** [comment]
Hi Guys. Any updates on the new Smilies?

Can we simply replace the emojis.json file with a new file?

**Comment by vdurmont** [comment]
Hey sorry the holidays took all my time and I couldn't work on this.
I started adding the new emojis to the json file.... Hope to be able to finish this weekend.

**Comment by vdurmont** [comment]
I finally had the time to update the emoji database!

I started the release of `v3.3.0` with all the new iOS 9.1 emojis, it should be available in maven central in a few hours. :rocket:

**Comment by robertmarkbram** [comment]
Thank you!
