### ISSUE TITLE
Emoji parsing

### ISSUE THREAD

**Issue by erwanlenagard** [vdurmont/emoji-java#115]
Hello, 

I'm trying to extract emojis from a text file where they aren't well encoded. 
For instance  : 
"lorem ipsum unicode-d83d\ude18"

I used Regex to transform the text into : 
"lorem ipsum \uD83D\uDE18"

When I try to call EmojiParser.parseToUnicode() or EmojiParser.parseToAliases() as written in the documentation, emojis aren't matched. How should I transform my text to extract emojis ? 

Thank you !

**Comment by milandimun** [comment]
Hi @erwanlenagard  is it still open ? I could work on this.

**Comment by erwanlenagard** [comment]
Hi ! 
Thank you. I found a solution using Regex. I'm a newbie programming Java, so there is probably a more straightforward solution to solve the issue...  

comment=comment.replaceAll("(unicode)-","\\\\u");
Pattern pattern_emoji = Pattern.compile("\\\\u(\\w*[0-9a-zA-Z]+\\w*[0-9a-zA-Z])");
Matcher  matcher_emoji = pattern_emoji.matcher(comment);
while (matcher_emoji.find()) {
	comment=comment.replace(matcher_emoji.group(),"");
	String emojitmp = matcher_emoji.group().toUpperCase();
	emojitmp=emojitmp.replace("U","u");
	comment=comment.replace(matcher_emoji.group(),emojitmp);
}
comment =StringEscapeUtils.unescapeJava(comment);
List<String> collectEmoji = EmojiParser.extractEmojis(comment);

**Comment by milandimun** [comment]
and do you have some another open issue which is not so difficult and i can work on it ? :D

**Comment by vdurmont** [comment]
Looks like this was resolved.
