### ISSUE TITLE
Memory performance

### ISSUE THREAD

**Issue by lijunkun1988** [vdurmont/emoji-java#116]
I use the library on an online system. When calling the method EmojiParser#parseToUnicode frequently, it costs a lot of memory which leads to very frequently GC.

When reading the code, I found that it called lots of String#replace for the parse function. Each String#replace will create a new String object. Thus, with more than 1000 emojis , each EmojiParser#parseToUnicode will create at least 2000 String objects which needs to be GC.

https://github.com/vdurmont/emoji-java/blob/master/src/main/java/com/vdurmont/emoji/EmojiParser.java#L145

I think maybe this can be improved by using a map for matching and a StringBuilder appending the rest.

**Comment by vdurmont** [comment]
This is a very good point. I won't have time to work on this soon (as you can imagine since I'm answering this issue 1 year late... sorry).

I would happily accept a PR that improves this! Please re-open if this is something you'd be ready to work on.
