### ISSUE TITLE
EmojiManager.isEmoji not working with text

### ISSUE THREAD

**Issue by hieuseesaa** [vdurmont/emoji-java#123]
EmojiManager.isEmoji("👍🏾") return true
EmojiManager.isEmoji("👍🏾👍🏾") return false
EmojiManager.isEmoji("👍🏾hello") return false. 
Please fix

**Comment by jackyhieu** [comment]
EmojiManager.isOnlyEmojis("👍🏾👍🏾") return true
EmojiManager.isOnlyEmojis("👍🏾👍🏾hello") return false

**Comment by invzbl3** [comment]
Please, fix it. Strill it doesn't work properly.

**Comment by SimonOrJ** [comment]
There should be a `containsEmoji()` method

**Comment by invzbl3** [comment]
@SimonOrJ, are you sure that this method exists? I don't have `containsEmoji()` using version 4.0.0 of vdurmont lib.
![11](https://user-images.githubusercontent.com/24904825/55681383-a568fe80-592e-11e9-898f-7819fac0f782.PNG)

**Comment by hieuseesaa** [comment]
@invzbl3  fix temporary errors

in kotlin . 

            if (EmojiParser.extractEmojis(text).isNotEmpty()) {
               
            }

**Comment by invzbl3** [comment]
@hieuseesaa thanks for an idea. In Java I get very similar to your solution. I didn't find `isNotEmpty()`, but the same logic:

![35](https://user-images.githubusercontent.com/24904825/55750519-20740700-5a4c-11e9-908b-530c48fd7cdf.PNG)


```
if(!EmojiParser.extractEmojis(update.getMessage().getText()).isEmpty()){
// code here
}
```

**Comment by SimonOrJ** [comment]
I was actually commenting about there should be `containsEmoji()` method in here to avoid confusion >_<

**Comment by invzbl3** [comment]
@SimonOrJ, ah, okay. I agree with you.

**Comment by vdurmont** [comment]
I agree, we should add a `containsEmoji` method. I'll look into it when I can, unless one of you wants to send a PR :)
