### ISSUE TITLE
🤩 this emoji not support

### ISSUE THREAD

**Issue by brightliming** [vdurmont/emoji-java#130]
🤩 this emoji not support

**Comment by weiyongyuan** [comment]
🧐this too!

**Comment by cw760** [comment]
🤯 too...
Is there anyone tell me how to support the extra emojis?

**Comment by brightliming** [comment]
@cw760 
package com.troila.http.utils;

public class EmojiUtil {
    // 转化emoji 成为 数字
    public static String filterEmoji(String source) {
        System.out.println("进行校验——>" + source);
        if (!containsEmoji(source)) {
            return source;// 如果不包含，直接返回
        }
        StringBuilder buf = null;
        int len = source.length();
        int isFirst = 1; 
        for (int i = 0; i < len; i++) {
            char codePoint = source.charAt(i);
            if (!isEmojiCharacter(codePoint)) {
                if (buf == null) {
                    buf = new StringBuilder(source.length());
                }
                buf.append(codePoint);
            } else {
                if (buf == null) {
                    buf = new StringBuilder(source.length());
                }
                if (isFirst == 1) {
                    buf.append("&#").append((int) codePoint).append("-");
                    isFirst = 0;
                } else {
                    buf.append((int) codePoint).append("&#");
                    isFirst = 1;
                }
            }
        }
        if (buf == null) {
            return "";
        } else {
            if (buf.length() == len) {// 这里的意义在于尽可能少的toString，因为会重新生成字符串
                buf = null;
                return source;
            } else {
                System.out.println("转译结果——>" + buf.toString());
                return buf.toString();
            }
        }
    }
    
    // 翻译emoji
    public static String analysisEmoji(String source) {
        if (!isEmojiStr(source)) {
            return source;// 如果不包含，直接返回
        }
        StringBuffer sBuffer = new StringBuffer();
        String[] split = source.split("&#");
        for (String string : split) {
            if (isEmojiNum(string)) {
                String[] split2 = string.split("-");
                for (String string2 : split2) {
                    int parseInt = Integer.parseInt(string2);
                    char codePoint = (char)parseInt;
                    sBuffer.append(codePoint);
                    continue;
                }
                continue;
            } else {
                sBuffer.append(string);
            }
        }
        return sBuffer.toString();
    }

    // 判别是否包含Emoji表情
    private static boolean containsEmoji(String str) {
        int len = str.length();
        for (int i = 0; i < len; i++) {
            if (isEmojiCharacter(str.charAt(i))) {
                return true;
            }
        }
        return false;
    }
    
    // 判别是否是Emoji表情的转译字符
    private static boolean isEmojiNum(String str) {
        String regex = "^(\\d{5}-\\d{5})$";
        return str.matches(regex);
    }

    private static boolean isEmojiCharacter(char codePoint) {
        return !((codePoint == 0x0) || (codePoint == 0x9) || (codePoint == 0xA) || (codePoint == 0xD)
                || ((codePoint >= 0x20) && (codePoint <= 0xD7FF)) || ((codePoint >= 0xE000) && (codePoint <= 0xFFFD))
                || ((codePoint >= 0x10000) && (codePoint <= 0x10FFFF)));
    }

    private static boolean isEmojiStr(String codePoint) {
        String regex = "^.*(&#\\d{5}-\\d{5}&#).*$";
        // String regex = "[1-9]\\d{4,14}";
        return codePoint.matches(regex);
    }
}

**Comment by cw760** [comment]
@brightliming 需要维护src/main/resources/emojis.json

**Comment by Pluckypan** [comment]
you can add your emoji to emojis.json

**Comment by sinboun** [comment]
you can use this!  It will support the latest emojis.json！ https://github.com/sinboun/emoji-java

**Comment by vdurmont** [comment]
I updated the `emojis.json` file in 1f26548, it should fix the problem. I will release a new version soon with those updates.
