### ISSUE TITLE
These emoji cannot display on swing JTextArea and JButton in Windows10

### ISSUE THREAD

**Issue by Moresweet** [vdurmont/emoji-java#131]
I am a student, I want to use these emojis on my project. When I running in terminal,it is normal to display.But in the swing compent ,it does not work. But if I set font as "Segoe UI Emoji". It can display emoji and have not color. If I change the font, my chinese words is can not be displyed. I want to find the solution. Thanks

**Comment by Pluckypan** [comment]
you can add your emoji to emojis.json

**Comment by Moresweet** [comment]
> try NotoColorEmojiCompat.ttf

Thanks for your reply. This solution is executable. I have already sloved this problem. I use the style of calligraphy called "Semoge UI" inWindows. And then it can display. Thanks again.

**Comment by vdurmont** [comment]
Looks like this was resolved.

**Comment by raydac** [comment]
looks like that it is [bug on level of java](https://bugs.openjdk.java.net/browse/JDK-8148555)
could you try 1.4.10-SNAPSHOT with latest embedded JDK?
