### ISSUE TITLE
isEmoji not detecting multiple emoji

### ISSUE THREAD

**Issue by 0lumide** [vdurmont/emoji-java#14]
If you pass a string containing a single emoji to the isEmoji method, it returns true as expected
but if you pass a sttring containing only two emojis, it returns false

``` java
EmojiManager.isEmoji("😄");  //returns true
EmojiManager.isEmoji("😄😃"); //returns false
```

Is this the intentional behaviour?

**Comment by vdurmont** [comment]
Yes, for me it was a way to detect if the string is **1** emoji.
But I definitely understand why you would need the second case to return `true`.
We could add a method like `isOnlyEmojis` or something like that. What do you think?

**Comment by 0lumide** [comment]
I was thinking of modifying isEmoji to return true in both cases, primarily because the method name doesn't hint that the parameter is supposed to be a single emoji. 

The other reason I was thinking of modying `isEmoji` is because, if `isOnlyEmojis` get's added, `isEmoji` would be a subset of `isOnlyEmojis` since `isOnlyEmojis` can always be used instead of `isEmoji`. So adding `isOnlyEmojis` would introduce some sort of redundancy in my opinion.

**Comment by Lolologist** [comment]
2 new methods would cover all cases I might imagine, namely "containsAnyEmoji" and "containsOnlyEmoji"? And, come to think of it, @0lumide is right that a method "containsOnlyEmoji" would cover the case of a single token string of one emoji. Of course, you'd then have to have an extra test of the length of the string or some such, to accomplish the actual specific case you have for isEmoji right now.

**Comment by castielfang** [comment]
I need this patch too.sometime we need to judge a String contains emoji for some business,but isEmoji cannt work.so @vdurmont would u fix this issues as @Lolologist's suggest?

**Comment by him2016** [comment]
What will the output be if there is a space between 2 emojis?
`EmojiManager.isEmoji("😄 😃");`
