### ISSUE TITLE
Standard heart seems to be mis-labeled

### ISSUE THREAD

**Issue by praveen-srinivasan** [vdurmont/emoji-java#15]
From the json in master:

{
    "emoji": "❤️",
    "description": "heavy black heart",
    "aliases": [
      "heart"
    ],
    "tags": [
      "love"
    ]
  },

**Comment by praveen-srinivasan** [comment]
Actually, now I'm not sure, per this article: http://emojipedia.org/heavy-black-heart/

But the name is confusing...

**Comment by vdurmont** [comment]
The description refers to the `black` keyword in unicode.

> Black: When describing pre-emoji Unicode symbols, black in a character names refers to the symbol being solid/filled in.

It just means that the emoji is filled in with the color. I understand why it may be misleading and we could choose to update the description if we have something better!
