### ISSUE TITLE
getAllEmojis returns duplicate emojis

### ISSUE THREAD

**Issue by praveen-srinivasan** [vdurmont/emoji-java#16]
I think this returns duplicate Emojis - maybe return a Set of some kind?

    public static Collection<Emoji> getAll() {
        return EMOJIS_BY_ALIAS.values();
    }

**Comment by praveen-srinivasan** [comment]
Concrete example: the thumbs up emoji, which has 2 aliases, appears twice:

{
    "emoji": "👍",
    "description": "thumbs up sign",
    "supports_fitzpatrick": true,
    "aliases": [
      "+1",
      "thumbsup"
    ],
    "tags": [
      "approve",
      "ok"
    ]
  },

**Comment by vdurmont** [comment]
Yes you're right, we should use a Set to avoid duplicates.
