### ISSUE TITLE
"Ear" and "Nose" should support fitzpatrick modifier

### ISSUE THREAD

**Issue by Lolologist** [vdurmont/emoji-java#18]
They don't, in the json. But they do on iOS.

Code change:
line 1040:
{
    "emoji": "👂",
    "description": "ear",
    "supports_fitzpatrick": true,
    "aliases": [
      "ear"
    ],
    "tags": [
      "hear",
      "sound",
      "listen"
    ]
  },

line 1065:
{
    "emoji": "👃",
    "description": "nose",
    "supports_fitzpatrick": true,
    "aliases": [
      "nose"
    ],
    "tags": [
      "smell"
    ]
  },

**Comment by vdurmont** [comment]
You're right! Will you send a PR?

**Comment by Lolologist** [comment]
Sure, why not! It's about time I figured out how to actually contribute For Realsies to projects like this.

BTW, you are awesome and I love this project.

**Comment by vdurmont** [comment]
Thanks :heart: I'll wait for your PR then!

**Comment by Lolologist** [comment]
Best i can tell, I did it right! Let me know. :)
