### ISSUE TITLE
Is the repo abandoned?

### ISSUE THREAD

**Issue by Homyakin** [vdurmont/emoji-java#195]
3 years since the last commit. Many emojis are no longer processed.

Are there any alternatives? Or is it possible to add missing emojis?

**Comment by andrefa** [comment]
should we fork it and continue to provide updates?

**Comment by Homyakin** [comment]
> should we fork it and continue to provide updates?

If someone does it, it will be perfect.

**Comment by goodale** [comment]
i'm wondering the same thing and curious how this (outdated) library compares to icu4j.  

While the purposes of two libraries is slightly different they both appear to serve the purpose of identifying Emoji's in strings so they can be automatically removed during server-side validation if needed.

icu4j appears to be updated regularly (latest update is 2022-12-20)

Note:  icu4j isn't really a viable option for web applications as the library is >10MB in size.

If there were a universal regex string that is regularly updated it would be possible to just use built in Java methods to remove emoji by passing that string.

**Comment by ouachman** [comment]
Hello everyone. On my side I am using a fork from https://github.com/jefersonbitencourtv/emoji-java for the time being as it support Emojis 13.1. But it would be great to have this library maintained (there are a bunch of pull requests ready to add missing emojis).

**Comment by Homyakin** [comment]
I find this repo https://github.com/felldo/JEmoji and will use it
