### ISSUE TITLE
Backwards Compatibility

### ISSUE THREAD

**Issue by Lolologist** [vdurmont/emoji-java#20]
I don't know if this is an 'issue' or not, but using this library to parse for, say, an Android device will have non-optimal results if a Unicode 8.0 emoji comes in.

Though fitzpatrick modifiers can be removed, 'unsupported' emoji may want to have an alternative (for example, for those parsing from, and then back to, emoji). A zipper-face emoji could be transformed to a regular face, as one example.

This issue will hopefully EVENTUALLY be overcome by events when Android has up-to-date emoji support, but will also be necessary for at least some time for iOS devices without the latest update after they are added, after Unicode 9.0 comes out sometime this year.

**Comment by vdurmont** [comment]
One of the solutions would be to add this information in the `emojis.json` file and to provide a way to specify which compatibility level we want.
The "code" part should be pretty easy but the hard work will be to enter the information in the json file... Thoughts?

**Comment by Lolologist** [comment]
The easiest change is the fitzpatrick modifier ignorer. With some sort of flag, perhaps, you can lop off any of those modifiers.

The harder one is exactly what you alluded to, the manual selection of "appropriate" covered emoji for those platforms that don't have all of them in.

**Comment by vdurmont** [comment]
No movement on this issue, I'm closing for now.
