### ISSUE TITLE
Some Emojis Not Supported

### ISSUE THREAD

**Issue by rfarmaha** [vdurmont/emoji-java#22]
It seems like the :sunglasses: emoji isn't being parsed correctly for me. Is this a known issue?

**Comment by vdurmont** [comment]
It's supposed to be supported (see https://github.com/vdurmont/emoji-java/blob/master/src/main/resources/emojis.json#L416)

What's the issue exactly?

**Comment by rfarmaha** [comment]
I have a string that contains the code point of the sunglasses emoji. When  I call `EmojiParser.parseToAliases` the resultant string shows garbage values rather than `:sunglasses:`

**Comment by Lolologist** [comment]
Confirmed. Cause was alias "sunglasses" existing twice, once for "dark sunglasses" and once for "Smiling Face With Sunglasses."

I'll make a fix.

**Comment by rfarmaha** [comment]
Awesome. Thanks

**Comment by vdurmont** [comment]
See #24
