### ISSUE TITLE
Emoji "" not included

### ISSUE THREAD

**Issue by seinecle** [vdurmont/emoji-java#23]
Could this emoji be included? 😂
It is a common one in social media
http://apps.timwhitlock.info/unicode/inspect?s=%F0%9F%98%82

Thanks!!

**Comment by vdurmont** [comment]
It is! https://github.com/vdurmont/emoji-java/blob/master/src/main/resources/emojis.json#L225

What's the issue exactly? Which method doesn't pick it up?

**Comment by Lolologist** [comment]
FWIW, it definitely works for me.

**Comment by vdurmont** [comment]
@seinecle , can you give us a failing test case so we can look into it?

**Comment by seinecle** [comment]
Hi,
Thanks for following up on the issue. I'll double check on my side but it seems I made a mistake.

**Comment by seinecle** [comment]
I understand the issue: I tried to find the emoji in those listed in the readme.md, which is incomplete. But indeed it is in the json file: https://github.com/vdurmont/emoji-java/blob/master/src/main/resources/emojis.json
