### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Lolologist** [vdurmont/emoji-java#25]
EmojiLoader:InputStreamToString has a Scanner that's never closed.

In applications that stay alive and call this project completely from scratch, it's possible this will eventually cause a failure.

**Comment by vdurmont** [comment]
Yes, you're right. I must have forgotten to close the stream. I've also been meaning to change the way we read the emojis database (see #17).

**Comment by vdurmont** [comment]
I removed the `Scanner` to use a `BufferedReader` in f0e4848dabcf8be0c5774632f6e7cf71bfc33c9c.

It should be ok now! Feel free to reopen if I made a mistake :smile:
