### ISSUE TITLE
Fail with EmojiParser.parseToAliases()

### ISSUE THREAD

**Issue by BackPackerDz** [vdurmont/emoji-java#30]
Hi when I call  EmojiParser.parseToAliases() for example  "😀😃"

I have this result :
:grinning:��

But if use it like this "😀 😃" it works !

**Comment by freva** [comment]
Confirmed, this is fixed in #29, which also includes a test for this type of problem.

**Comment by vdurmont** [comment]
I merged #29 (thanks again @freva ) so this should be fixed in v3.1.1.
I just released it and it should be available on maven central within a few hours.

Please reopen if you still have this issue after upgrading.
