### ISSUE TITLE
Parsing no longer works when exported as jar file

### ISSUE THREAD

**Issue by manuelgu** [vdurmont/emoji-java#33]
Hello,

I'm using `EmojiParser.parseToAliases(message)` to convert emojis to to their aliases.

I'm reading messages from a third-party application which contain emojis.

I have two applications set up, one which I'm running from IntelliJ and one which is being exported as a .jar fille and executed via `java -ver blah.jar`

Whilst the pure Java application successfully parses the emoji to an alias, the [exact same code](http://hastebin.com/misucisaju.avrasm) exported as a .jar does not parse the emoji at all and still returns the emoji from `EmojiParser.parseToAliases()`.

Happy to share some more code, thanks.

**Comment by manuelgu** [comment]
Turns it this is an issue when the emoji-java is exported in a jar file in general. Updated main post.

**Comment by jppommet** [comment]
same issue here, we are using gradle shadow plugin 1.2.3

**Comment by jppommet** [comment]
@manuelgu Not sure if you tried this but in the file `emojis.json` you would notice that the emojis are unicode, let's replace the sunglasses emoji by its UTF-16 hex character "\uD83D\uDE0E" for example. Run your program in your IDE and as a jar, it should normally convert the emoji to its alias (short code).
Let me know if it worked for you.

**Comment by Lolologist** [comment]
A good idea; I'll give it a shot sometime soon.

-Daniel

**Comment by manuelgu** [comment]
My IntelliJ terminal has UTF-8 encoding (that is why it works) while the Windows Powershell uses Windows-1252. I couldn't figure a way to change that, but since my application is running on a linux terminal in bash it doesn't really matter, because that one has UTF-8 encoding as well.

Replacing the emojis in the file sounds like a great idea though!
