### ISSUE TITLE
parseToAliases not work 

### ISSUE THREAD

**Issue by 88250** [vdurmont/emoji-java#34]
3.0.0 is ok, but the newer version 3.1.0 and 3.1.1 dose not work.

**Comment by Lolologist** [comment]
Hi,

Can you please give us some sample code? I have a project that relies heavily on this library and I'm having no issues other than incomplete emoji coverage, and Darn Kids somehow managing to use Regional Indicator Symbols independently of the flags they're supposed to make. But that's neither here nor there.

Point is, I see parseToAliases working just fine.

**Comment by 88250** [comment]
@Lolologist Uses the v3.1.0 or v3.1.1 could produce this issue.

**Comment by vdurmont** [comment]
@88250 , please provide us a concret example that is not working with:

- The string in input
- The string in output
- The string that you expected to have in output
- The code you are using

It is really hard to help you without this context :)

**Comment by 88250** [comment]
@vdurmont 

The sample code: 

```java
public static void main(String[] args) {
    String str1 = "Here is a boy: \uD83D\uDC66\uD83C\uDFFF!";
    String str2 = EmojiParser.parseToAliases(str1, EmojiParser.FitzpatrickAction.REMOVE);

    System.out.println(str2);
}
```

The output is OK with v3.0.0: 
```
Here is a boy: :boy:!
```

But v3.1.1 outputs: 
```
Here is a boy: ??!
```

In debugging view: 

![image](https://cloud.githubusercontent.com/assets/873584/15168163/6cfe25f0-1761-11e6-9353-6d57ee6c2a98.png)

----

I uses Maven central repository to setup emoji-java.

Env info: 

* Java: 1.8.0_60; Java HotSpot(TM) 64-Bit Server VM 25.60-b23
* OS: Windows 10 version 10.0 running on amd64
