### ISSUE TITLE
getting all emojis from string

### ISSUE THREAD

**Issue by gidim** [vdurmont/emoji-java#37]
Hi,

Is there a better way to extract all emojis from a string?
This is what i'm doing atm

```
    public ArrayList<String> getAllEmojis(String str) {
        ArrayList<String> emojis = new ArrayList<>();
        for (Emoji emoji : EmojiManager.getAll()) {
            if (str.contains(emoji.getUnicode()))
                emojis.add(emoji.getUnicode());
        }
        return emojis;
    }
```

**Comment by vdurmont** [comment]
It's going to work for simple emojis but you're not going to extract the fitzpatrick modifiers with this code.
What's the use case?

You can take a look at `EmojiParser.parseFromUnicode` to see how we detect the emojis: https://github.com/vdurmont/emoji-java/blob/master/src/main/java/com/vdurmont/emoji/EmojiParser.java#L349

**Comment by gidim** [comment]
Basically trying to count frequency of Emojis over a string.
After I return from the above function I sort by frequency.
Eventually I need to create a string with the top N emojis so I do want to have the Fitzpatrick Modifiers.

Will `getUnicodeCandidates()` return a list of all emojis in a string?

**Comment by gidim** [comment]
Also getUnicodeCandidates() is protected ):

**Comment by roberterdin** [comment]
+1

**Comment by freva** [comment]
The only problem I see is that the `EmojiParser` constructor is `private`, it should be protected so that you could extend EmojiParser, then you can on top of that to make your frequency code, for example:

```java
public class EmojiFrequency extends EmojiParser {
    private Map<Emoji, Integer> frequencies = new HashMap<Emoji, Integer>();

    public EmojiFrequency() {
        super();
    }

    public void updateFrequencies(String text) {
        for(UnicodeCandidate uc : getUnicodeCandidates(text)) {
            frequencies.put(uc.getEmoji(), frequencies.getOrDefault(uc.getEmoji(), 0) + 1);
        }
    }

    public Map<Emoji, Integer> getFrequencies() {
        return frequencies;
    }
}
```

and then

```java
    public static void main(String[] args) throws FileNotFoundException {
        EmojiFrequency ef = new EmojiFrequency();
        Scanner scanner = new Scanner(new File("textWithEmojis.txt"));
        while (scanner.hasNext()) {
            ef.updateFrequencies(scanner.nextLine());
        }

        for (Map.Entry<Emoji, Integer> entry : sortByValue(ef.getFrequencies()).entrySet()) {
            System.out.println(entry.getKey().getAliases().get(0) + " | " + entry.getValue());
        }
    }
```

**Comment by roberterdin** [comment]
setting `getUnicodeCandidates()` public works for me, just testet that. Your solution is a bit more versatile though.

**Comment by vdurmont** [comment]
I'm thinking about which solution is the best one.

I initially defined a private constructor for `EmojiParser` because I wanted it to be an utility class and didn't think it would be interesting to extend it.

It looks like some of you could benefit from extending it so I'm wondering if I should make it extendable or just set `getUnicodeCandidates` public.

I am leaning towards enable `EmojiParser` to be extended. Any thoughts?

**Comment by freva** [comment]
I `EmojiParser` should be extended by those who require some additional functionality. Functions like `getUnicodeCandidates` and `getAliasCandidates` a by themselves aren't super useful, so people will still need to write some own functions on top of that, exposing them to all users will probably will just clutter the API.

**Comment by vdurmont** [comment]
It should be good now. Feel free te reopen the issue if you need something else :)

**Comment by roberterdin** [comment]
Will you publish a new version to the Maven Central?

**Comment by vdurmont** [comment]
Yes! Look out for v3.1.2, it should be up today!
