### ISSUE TITLE
Missing Fitzgerald types

### ISSUE THREAD

**Issue by Lolologist** [vdurmont/emoji-java#42]
Is there a reason that person_with_ball and weight_lifter have supports_fitzpatrick set to false?

Also, :v: and :point_up: and :bow: didn't have the setting.

I'm working on a branch and after I hear back I can make a pull request.

**Comment by searchy2** [comment]
I can confirm that person_with_ball and weight_lifter are supposed to have fitzpatrick set to true. Currently, I am working on adding 400 new and missing emoticons to the emoji.json list!

**Comment by vdurmont** [comment]
We can definitely add support for fitzpatrick for these emojis! @Lolologist, feel free to send a PR or we'll get to it when merging @searchy2 's PR.
