### ISSUE TITLE
New Emoji's Not Yet Added?

### ISSUE THREAD

**Issue by searchy2** [vdurmont/emoji-java#44]
Hi! It appears that the emoji database is current as of Unicode 8.0. Unicode 9.0 and above emojis are not supported? Can someone please confirm that is the case?
In addition, is the emoji database still based on gemoji? Gemoji's emoji registry has not been updated for 5 months. 
Updating emoji.json is very quick and easy and I can submit a commit right away.

**Comment by vdurmont** [comment]
Hi!
The database was originally based on Gemoji but I added a lot of emojis since then (see 08493ba32d5f408af79ef5b7c052f799b49be763 for example).
I did not update the DB recently so I probably some emojis are probably missing.
If you want to add more emojis, feel free to submit a PR!

**Comment by searchy2** [comment]
Will do!

**Comment by searchy2** [comment]
Quick question, where did you obtain the aliases for the emoticons? I don't see them from the official list of UNICODE emoticons @http://unicode.org/emoji/charts/full-emoji-list.html 
Thanks for the assistance!

**Comment by vdurmont** [comment]
There is no official list. Here's how I did it:
- I took the first ones from Gemoji
- I took a look at emojipedia which has several descriptions
- I invented some of them

Just pick something that makes sense :)

**Comment by searchy2** [comment]
Thank you for the reply! Right now, I'm alternating between :cry: and :joy: because YOU are the official list. Full disclosure, I am currently working on QKSMS's emoji support and to update its emojis, I must update the source which is your repo. There's 72 new emojis in UNICODE 9.0 so this should be fun :expressionless:

**Comment by searchy2** [comment]
This update is taking a bit longer than expected. I have put in about 6 hours of work so far and named over 200 emojis. Unfortunately, there were over 400 emojis missing; not the 100 that I initially thought. This will take a few more hours to complete. Probably by tomorrow :pray:

**Comment by searchy2** [comment]
Ok, the emoji list has been updated to include every single emoji currently in the UNICODE specifications. All that is left is to convert the Excel spreadsheet back into json format and commit. :laughing:
