### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by AnkurJagani** [vdurmont/emoji-java#52]
Hi, Would you please help me with this exception. if possible. Thanks in advance. 

![no_class_found_error](https://cloud.githubusercontent.com/assets/7710697/18629970/fda0c400-7e86-11e6-878d-68110d227c40.PNG)

i am using compile 'com.vdurmont:emoji-java:3.1.3' in gradle file.

**Comment by vdurmont** [comment]
The error says that the class `EmojiParser` is not on your path.
How do you build your project?
Do you use a dependencies manager such as Maven? If not, you have to manually make sure that this class is on your path.

**Comment by AnkurJagani** [comment]
yes i am not using Maven. i am giving dependency in gradle build file. i.e. compile 'com.vdurmont:emoji-java:3.1.3'.  While gradle do i need to set path manually?

**Comment by cyriltw** [comment]
I'm having the same issue.

**Comment by tvaidya** [comment]
Any solution on this ?
