### ISSUE TITLE
NoClassDefFoundError: org/json/JSONArray

### ISSUE THREAD

**Issue by whitecat** [vdurmont/emoji-java#54]
I download release and add the jar to my build path.
Then I add code:

```
String input = "A string 😄with a \uD83D\uDC66\uD83C\uDFFFfew 😉emojis!";
String result = EmojiParser.removeAllEmojis(input);
```

I get the error: `NoClassDefFoundError: org/json/JSONArray`

I found http://mvnrepository.com/artifact/org.json/json/20080701 which has a JSONArray class. But is that the correct JSONArray?

**Comment by Lolologist** [comment]
You want this as a dependency in your project:

https://github.com/stleary/JSON-java

**Comment by whitecat** [comment]
Is that in the readme?

**Comment by vdurmont** [comment]
The README gives instructions to use the project with a package manager (Maven, Gradle...).
If you don't use any package manager, you have to resolve the dependencies yourself.

Feel free to send a PR to update the README with instructions if you want to help the next developer :)

**Comment by vdurmont** [comment]
And yeah, I used http://mvnrepository.com/artifact/org.json/json/ (see pom.xml)

**Comment by whitecat** [comment]
Submitted a pull request.
