### ISSUE TITLE
v3.1.3 Source Doesn't Include #45 (Added emojis introduced in Unicode 9.0)

### ISSUE THREAD

**Issue by solamour** [vdurmont/emoji-java#56]
According to v3.1.3 release note (https://github.com/vdurmont/emoji-java/compare/v3.1.3...master), pull request #45 is included. And when I do "git clone ...", I do see additional 72 emojis added by #45, which results in total 1347 emojis.

But I see only 1275 emojis (i.e. 72 emojis missing) if I do one of the following.
1) In Gradle, add "compile 'com.vdurmont:emoji-java:3.1.3'".
2) Download "https://github.com/vdurmont/emoji-java/archive/v3.1.3.tar.gz" and check "src/main/resources/emojis.json" file.
3) Download "https://github.com/vdurmont/emoji-java/archive/v3.1.3.zip" and check "src/main/resources/emojis.json" file.
4) Download "https://github.com/vdurmont/emoji-java/releases/download/v3.1.3/emoji-java-3.1.3.jar" and use "compile files('libs/emoji-java-3.1.3.jar')" in Gradle.

It looks like the 3.1.3 tag is placed at a wrong place.

`* a616dd3 (HEAD -> master, origin/master, origin/HEAD) Update README include location of direct download in how to git, and download of necessary dependencies. (#55)`
`* 3ace39c Added emojis introduced in Unicode 9.0 (#45)`
`* 261dc28 Fixed tag of the Poland flag (#43)`
`* f06c0e3 (tag: v3.1.3) Release v3.1.3       <-- ??`
__
sol

**Comment by Tapchicoma** [comment]
Any plans to make fix release 3.1.4?

**Comment by vdurmont** [comment]
Yes, I will release a new version soon.
