### ISSUE TITLE
Remove All Emojis not remove complete

### ISSUE THREAD

**Issue by renatobezerra** [vdurmont/emoji-java#60]
I have a issue when use EmojiParser.removeAllEmojis() method.

The String unicode is "Name ❤️  lastname". After using this method, the returned string is "Name  Lastname", but between names, have a another chars that not is blank spaces.

**Comment by Lolologist** [comment]
Paste the code into an online Unicode inspector. Google it, easy enough to
find.

Is what remains a Variation Selector 16?

**Comment by susil1k** [comment]
I have a issue when use EmojiParser.removeAllEmojis() method.

I have the String unicode is "🍁Test comment". After using this method, the returned string is "ߍTest comment", It have another character.
