### ISSUE TITLE
Library does not recognize new iOS 10.2 emojis

### ISSUE THREAD

**Issue by fabricapo** [vdurmont/emoji-java#62]
There are a bunch of new emojis in iOS 10.2 (see http://blog.emojipedia.org/ios-10-2-emoji-changelog/) and it does not seem the parser recognizes them. 

All the new emojis are here: http://emojipedia.org/apple/ios-10.2/new/

**Comment by fabricapo** [comment]
That is awesome. Do you plan to have a new release soon, or shall I download the source code and build it?

**Comment by vdurmont** [comment]
I just sent a new release to maven central, it should be available for download in a few hours.

**Comment by fabricapo** [comment]
Fantastic!

fabrizio

On Feb 12, 2017, at 17:17, Vincent Durmont <notifications@github.com<mailto:notifications@github.com>> wrote:


I just sent a new release to maven central, it should be available for download in a few hours.

**Comment by vdurmont** [comment]
Should be ok now: https://search.maven.org/#artifactdetails%7Ccom.vdurmont%7Cemoji-java%7C3.2.0%7Cjar
