### ISSUE TITLE
IPhone keyboard emoji couldn't recognize.

### ISSUE THREAD

**Issue by nuancat** [vdurmont/emoji-java#63]
I have a working project no recognizing apple emojis. No recognizing emojis is 1995 emoji year.
It lists "http://unicode.org/emoji/charts/full-emoji-list.html"

**Comment by nuancat** [comment]
Issue in method - EmojiManager.isEmoji(String)

**Comment by vdurmont** [comment]
I'm sorry, I don't really understand the issue. Can you provide a failing test case or an example?
