### ISSUE TITLE
There is an error in repackaged after running

### ISSUE THREAD

**Issue by zhimin568** [vdurmont/emoji-java#66]
5-Mar-2017 16:08:34.911 SEVERE [http-nio-8080-exec-8] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [spring] in context with path [evy_interfaces] threw exception [Handler processing failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class com.vdurmont.emoji.EmojiManager] with root cause
 java.lang.NoClassDefFoundError: Could not initialize class com.vdurmont.emoji.EmojiManager

why：After repackaging, found itself without a jar (org.json)

**Comment by vdurmont** [comment]
Not sure how I can help with this, it is not an issue with the library but with your setup.
