### ISSUE TITLE
Not all unicode 9.0 emoji are available

### ISSUE THREAD

**Issue by Tapchicoma** [vdurmont/emoji-java#69]
Currently emoji.json missing definition for 1665 emoji from unicode 9.0 standard. Need to add them as well.

**Comment by vdurmont** [comment]
Happy to accept a pull request for this!

**Comment by Tapchicoma** [comment]
@vdurmont the problem here is with emoji that has fitzpatric modifier in the middle of it's unicode, for example:
🙎🏻‍♂️ - [Man pouting: light skin tone](https://emojipedia.org/man-pouting-type-1-2/).

As `EmojiTrie` doesn't include fitzpatric modifiers on the build time - it fails to detect such emoji.

Possible solutions:
- Treat gender modifiers the same way as fitzpatric modifiers.
- Include also fitzpatric in the `EmojiTrie` on build time

What do you think?

**Comment by vdurmont** [comment]
I suppose it'd be interesting to treat it like a fitzpatrick modifier. Do you think it's the easiest solution?

**Comment by Tapchicoma** [comment]
Imho treating it like fitzpatric modifier. I will try to implement this.

**Comment by turbanoff** [comment]
♡ `White Heart Suit` is missing too

**Comment by wasnertobias** [comment]
:soup: and :coconut: is missing.

**Comment by jakobvogel** [comment]
#114 should add many missing emojis

**Comment by vdurmont** [comment]
I updated the `emojis.json` file in 1f26548, it should fix the problem. I will release a new version soon with those updates.
