### ISSUE TITLE
:-1: cannot be parsed to Unicode

### ISSUE THREAD

**Issue by jayther** [vdurmont/emoji-java#7]
`:-1:` currently cannot be parsed to :-1: (doesn't replace `:-1:` with the :-1: unicode). I think this is pretty similar to a closed isssue about :+1: . Parsing `:+1:` to :+1: still works.

Parsing `:thumbsdown:` works fine, but when I parse the thumbsdown unicode to alias, it returns as `:-1:`. Parsing this result back to unicode fails and just returns as `:-1:`.

**Comment by vdurmont** [comment]
You were right!
I'll release a new version with the fix asap

**Comment by vdurmont** [comment]
Version 2.0.1 has been published on Maven Central. Should be available in a few hours.

**Comment by jayther** [comment]
Awesome, thanks, it's indeed fixed!
