### ISSUE TITLE
Emoji problem like \uE30f  or \uExxx  this is iOS code?

### ISSUE THREAD

**Issue by VesperHan** [vdurmont/emoji-java#71]
hello
i have some trouble,when is use your sdk insert emoji to mysql,some emoji like \uE401 or \uExxx
cannot trans like emoji.json emoji's  description to mysql.

i think how to update emoji.json and i search google the emoji's list is a picture... embarrass..

so,i want to help, the start with \uExxx 's emoji, how to trans when use your emoji-java  

!!wait  I  saw some different such as  the emojis.json have tags is medicine 
emoji is \uD83d\uDC8A
the picture is\uE30f
why..... get got some people's nicknime is \uExxx .... im..... im surrender...

![image](https://user-images.githubusercontent.com/16316152/26972014-5cb52c3a-4d42-11e7-842f-7c0c3d9d5a14.png)

**Comment by vdurmont** [comment]
I'm really sorry but I'm not sure I understand what you issue is and how I can help.
