### ISSUE TITLE
Not all of the Emoji 5.0 emojis are available

### ISSUE THREAD

**Issue by predasorinionut** [vdurmont/emoji-java#72]
Is there any chance that the rest of the emojis in Emoji 5.0 that currently aren't available, to be added?

**Comment by vdurmont** [comment]
@predasorinionut Can you tell me which ones are not available? Feel free to send a PR, I'd be glad to accept it!

**Comment by Tapchicoma** [comment]
After fixing #69 we can apply new [emoji test data](http://www.unicode.org/Public/emoji/5.0/emoji-test.txt) and see what emoji are missing.

**Comment by runehammerskov** [comment]
Any news since july on when this might be looked at? I'm using this lib to remove emojis from texts and the new IOS 11 emojis are not supported yet.

**Comment by vdurmont** [comment]
@runehammerskov it is very unlikely that this is "going to get looked at" soon, I don't have a lot of time to work on it. However, I'll gladly accept your Pull Request that upgrades the emojis to support iOS 11!
