### ISSUE TITLE
"Trademark" emoji alias not working as expected

### ISSUE THREAD

**Issue by gkubisa** [vdurmont/emoji-java#73]
`EmojiParser#parseToUnicode(String)` should convert the `:tm:` alias to a [Trademark symbol](https://emojipedia.org/trade-mark-sign/), however, it converts it to a [Turkmenistan flag](https://emojipedia.org/flag-for-turkmenistan/).

**Comment by freva** [comment]
Looks like this was fixed in https://github.com/vdurmont/emoji-java/commit/d75b072acd97ccab4c32e1b9a07fcd079648580d#diff-78a227b97cc86c6908e813901e660768R10230

**Comment by gkubisa** [comment]
Yes, that should fix it. I see the change is on master but not in any of the releases yet (https://github.com/vdurmont/emoji-java/compare/v3.2.0...master). Could we get a new release containing those changes?

**Comment by vdurmont** [comment]
Yes I will send a new release this week!

**Comment by vdurmont** [comment]
I just released v3.3.0 https://github.com/vdurmont/emoji-java/releases/tag/v3.3.0
