### ISSUE TITLE
Question : no bug nor feature request

### ISSUE THREAD

**Issue by adriens** [vdurmont/emoji-java#74]
Hi, can you please tell me if you are referencing all the emoticons that are here :

https://www.webpagefx.com/tools/emoji-cheat-sheet/

I'm especially intersted in the slack ones ;-p

Thanks in advance for your answer.

**Comment by vdurmont** [comment]
Hi! I think we have all of them but I just took a quick look at the page.
The list of all the emojis we support is there: https://github.com/vdurmont/emoji-java/blob/master/src/main/resources/emojis.json
