### ISSUE TITLE
New artifact with extractEmojis?

### ISSUE THREAD

**Issue by dserban** [vdurmont/emoji-java#75]
I'm very interested in using `extractEmojis` however it was recently added and the current (`3.2.0`) artifact on Maven Central doesn't contain it.
Any idea when a new artifact is going to be published?

**Comment by vdurmont** [comment]
I can probably publish a new version next week!

**Comment by vdurmont** [comment]
I just released v3.3.0 https://github.com/vdurmont/emoji-java/releases/tag/v3.3.0
