### ISSUE TITLE
com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect string value: '\xF0\x9F\x98\xBA' for column 'content' at row 1

### ISSUE THREAD

**Issue by helloworldtang** [vdurmont/emoji-java#83]
use api: EmojiParser.parseToUnicode(answerReqVO.getContent()); 

but still fail ,like this below:
```sql
 : ==>  Preparing: INSERT INTO sns_answer ( content ) VALUES ( ?) 
 : ==> Parameters: 哈哈           😺(String)
```

### Cause: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect string value: '\xF0\x9F\x98\xBA' for column 'content' at row 1
; SQL []; Data truncation: Incorrect string value: '\xF0\x9F\x98\xBA' for column 'content' at row 1; nested exception is com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect string value: '\xF0\x9F\x98\xBA' for column 'content' at row 1

**Comment by vdurmont** [comment]
Hi, all this is your code. You have to setup the DB correctly to accept unicode. I can't help with that.
