### ISSUE TITLE
EmojiParser.parseToUnicode(...) doesn't parse medal emoji

### ISSUE THREAD

**Issue by ftemotheos** [vdurmont/emoji-java#95]
Some aliases for emoji (like first_place_medal, second_place_medal, thrid_place_medal) do not parse into unicode by method EmojiParser.parseToUnicode(someText). I guess, the same situation is with all emoji in the bottom of the available emoji's list.

**Comment by cbedoy** [comment]
I think would be a good feature

**Comment by freva** [comment]
Not sure what the problem is, did you wrap the alias inside `:`? Works here:
```
System.out.println(EmojiParser.parseToAliases(EmojiParser.parseToUnicode(":first_place_medal:")));
```
Gives
```
:first_place_medal:
```
