### ISSUE TITLE
Is this library Java 6 compliant? If not, is there a reason why it can't be?

### ISSUE THREAD

**Issue by bgreen1005** [vdurmont/emoji-java#99]
Hi,

Not sure if this is the best place to ask the question, or whether it's best to send an email. This looks like a great library, and i was just wondering if I would be able to use it in a java 6 project I am writing, or whether it requires a more recent version of java to run.

**Comment by vdurmont** [comment]
The library is java6 compliant. I didn't test it recently myself but our CI (https://travis-ci.org/vdurmont/emoji-java) runs on openjdk6.
